version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check

      # - run:
      #     name: Login to Docker Hub
      #     command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - docker/build:
          image: renraelreve77/education-space

      # - run:
      #     name: Build Docker Image
      #     command: docker build --file=./Dockerfile --tag=docker.io/renraelreve77/education-space:latest .

      - docker/push:
          image: renraelreve77/education-space

      # - run:
      #     name: Push Docker Image
      #     command: docker push docker.io/renraelreve77/education-space:latest

  scan:
    docker:
        - image: cimg/node:16.10
    environment:
        IMAGE_NAME: renraelreve77/education-space
    steps:
        - checkout
        - setup_remote_docker
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan:
            docker-image-name: $IMAGE_NAME
            severity-threshold: high
            fail-on-issues: false

  codescan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: edisonzsq/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/install
      - run: |
          snyk code test

  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: |
                heroku container:login
                heroku stack:set container -a renraelreve77-su-devops
                heroku container:push web -a renraelreve77-su-devops
                heroku container:release web -a renraelreve77-su-devops

workflows:
  simple_workflow:
    jobs:
      - build:
          name: build-main
          filters:
            branches:
              only: main
      - test:
          name: test-main
          requires:
            - build-main
          filters:
            branches:
              only: main
      - build:
          name: build-release
          filters:
            branches:
              only: release
      - test:
          name: test-release
          requires:
            - build-release
          filters:
            branches:
              only: release
      - build-and-push:
          name: build-and-push-release
          requires:
            - test-release
          filters:
            branches:
              only: release

# The scan job
      - scan:
          requires:
            - build-main
          filters:
            branches:
              only: main

      - codescan:
          requires:
            - build-main
          filters:
            branches:
              only: main

      - deploy:
          name: deploy-release
          requires:
            - build-and-push-release
          filters:
            branches:
              only: release
