version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.6.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo jiyuan2008 | docker login -u renraelreve77 --password-stdin
      - run:
          name: Build Docker Image
          command: docker build --file=./Dockerfile --tag=docker.io/renraelreve77/education-space:latest .
      - run:
          name: Push Docker Image
          command: docker push docker.io/renraelreve77/education-space:latest

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
                requires:
                  - test
